FROM mhart/alpine-node:10
MAINTAINER Stefano Straus <stefano+docker@straus.it>
# based on excellent work of Yeung Yiu Hung <hkclex@gmail.com> and others

# Install ClamAV and supervisord
# Debian Base to use
ENV CLAM_VERSION=0.101.1

# Install ClamAV and supervisor
RUN apk add --update \
        pax-utils \
        libattr \
        attr \
        tar \
        pkgconf \
        patch \
        lzip \
        ca-certificates \
        libssh2 \
        libcurl \
        curl \
        abuild \
        binutils-libs \
        binutils \
        gmp \
        isl \
        libgomp \
        libatomic \
        mpfr3 \
        mpc1 \
        gcc \
        musl-dev \
        libc-dev \
        g++ \
        make \
        fortify-headers \
        build-base \
        expat \
        pcre2 \
        git \
        lz4-libs \
        xz-libs \
        lzo \
        squashfs-tools \
        libburn \
        ncurses-terminfo-base \
        ncurses-terminfo \
        ncurses-libs \
        libedit \
        libacl \
        libisofs \
        libisoburn \
        xorriso \
        acct \
        lddtree \
        libuuid \
        libblkid \
        device-mapper-libs \
        cryptsetup-libs \
        kmod \
        mkinitfs \
        mtools \
        alpine-sdk \
        libxml2 \
        linux-headers \
        zlib-dev \
        libcrypto1.0 \
        libssl1.0 \
        openssl-dev \
        libbz2 \
        libffi \
        gdbm \
        readline \
        python2 \
        py-meld3 \
        py-setuptools \
        supervisor \
        wget \


RUN wget https://www.clamav.net/downloads/production/clamav-${CLAM_VERSION}.tar.gz && \
    tar xvzf clamav-${CLAM_VERSION}.tar.gz && \
    cd clamav-${CLAM_VERSION} && \
    ./configure && \
    make && make install && \
    rm -rf /var/cache/apk/*

RUN echo "/usr/lib" >> /etc/ld.so.conf.d/clamav.conf && \
    ldconfig -v

# Update Permission
RUN groupadd -r clamav && \
    useradd -r -g clamav -u 1001 clamav -d /var/lib/clamav && \
    mkdir -p /var/lib/clamav && \
    mkdir /usr/local/share/clamav && \
    mkdir /var/run/clamav && \
    mkdir /var/log/clamav && \
    mkdir /server && \
    chown -R clamav:clamav /server \
    /var/lib/clamav \
    /usr/local/share/clamav \
    /var/run/clamav \
    /usr/local/lib \
    /usr/local/etc/ \
    /var/log/clamav/ && \
    chmod 750 /var/run/clamav /server

# Initial update of av databases 
RUN wget -t 5 -T 9999 -O /var/lib/clamav/main.cvd http://database.clamav.net/main.cvd && \
    wget -t 5 -T 9999 -O /var/lib/clamav/daily.cvd http://database.clamav.net/daily.cvd && \
    wget -t 5 -T 9999 -O /var/lib/clamav/bytecode.cvd http://database.clamav.net/bytecode.cvd && \
    chown clamav:clamav /var/lib/clamav/*.cvd

# Volume provision
VOLUME ["/var/lib/clamav"]

WORKDIR /server

COPY . /server

RUN npm install && npm run postinstall && npm prune --production

# Copy supervisor and clam config
COPY ./configs/supervisord.conf /etc/supervisor/conf.d/supervisord-nodejs.conf
COPY ./configs/clamd.conf /etc/clamav/clamd.conf
COPY ./configs/freshclam.conf /etc/clamav/freshclam.conf 

EXPOSE 3000
CMD ["/usr/bin/supervisord", "-n"]